import { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";
import Navbar from "./components/navbar/Navbar";
import Footer from "./components/footer/Footer";

const inter = Inter({ subsets: ["latin"], weight: ["700", "800"] });

export const metadata: Metadata = {
  title: "Click.com",
  description: "Generated by create next app",
  icons: {
    icon: "https://icones.pro/wp-content/uploads/2021/06/cliquez-sur-le-symbole-orange.png", 
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="https://icones.pro/wp-content/uploads/2021/06/cliquez-sur-le-symbole-orange.png" />
        <link rel="icon" type="image/png" href="https://icones.pro/wp-content/uploads/2021/06/cliquez-sur-le-symbole-orange.png" />
      </head>
      <body className={`${inter.className}`}>
        <div className="flex flex-col min-h-screen">
          <Navbar/>
          <main className="flex-grow">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
